// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wledBridge.Infrastructure.Persistence;

#nullable disable

namespace wledBridge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WledBridgeDbContext))]
    [Migration("20260710134124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("wledBridge.Domain.Controllers.ControlMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ControllerDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalControlId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VirtualControlId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControllerDeviceId", "PhysicalControlId")
                        .IsUnique();

                    b.ToTable("ControlMappings", (string)null);
                });

            modelBuilder.Entity("wledBridge.Domain.Controllers.ControllerDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MidiInputDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MidiOutputDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ControllerDevices", (string)null);
                });

            modelBuilder.Entity("wledBridge.Domain.Controllers.VirtualControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VirtualMixerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VirtualMixerId");

                    b.ToTable("VirtualControls", (string)null);
                });

            modelBuilder.Entity("wledBridge.Domain.Controllers.VirtualMixer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VirtualMixers", (string)null);
                });

            modelBuilder.Entity("wledBridge.Domain.Wled.WledDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WledDevices", (string)null);
                });

            modelBuilder.Entity("wledBridge.Domain.Controllers.VirtualControl", b =>
                {
                    b.HasOne("wledBridge.Domain.Controllers.VirtualMixer", null)
                        .WithMany("Controls")
                        .HasForeignKey("VirtualMixerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wledBridge.Domain.Controllers.VirtualMixer", b =>
                {
                    b.Navigation("Controls");
                });
#pragma warning restore 612, 618
        }
    }
}
